# Create a file named index.html in your project directory and write a Dockerfile that copies this file into the /usr/share/nginx/html directory of an nginx Docker image.

FROM nginx:latest

WORKDIR /usr/share/nginx/html/

COPY index.html ./

EXPOSE 80
